### PR TITLE
Serve goal icons locally instead of remotely

### PR DESCRIPTION
**Pull request by brockfanning**
@mauromussin This PR is meant to demonstrate a few things:
1. In order for the goal icons to be served locally, I've moved them into the `www` folder under `assets`, so that they can be accessed by browsers.
2. This changes the `goal_image_base` setting to the local folder, instead of a remote URL. But because all goal icons have to be served from the same place, I also needed to copy in the English icons. (Though if you don't intend to use English, then this is not necessary.)
3. I've copied in the "high-contrast" versions of the English icons as well, to show where they would go. You'll want to eventually make high-contrast versions of the Italian icons you made (great work!).
4. I added an English translation file for `languages.yml`, so that the translation "Italiano" will work in the language-picker drop-down, when looking at an English page.
5. Just to keep things up to the cutting edge, I've included an upgrade of jekyll-open-sdg-plugins and sdg-build.

### CODE REVIEW

**Comment by brockfanning** [comment]
@mauromussin I needed to push up a couple more changes to allow tests to pass:
1. Placeholders for Italian versions of all the pages (About, FAQ, etc.) and posts.
2. A placeholder (the English version) for the Italian "goal 18" icon, which is mainly for symmetry in the homepage grid.

**Review by mauromussin — APPROVED** [review]

**Comment by mauromussin** [comment]
> @mauromussin I needed to push up a couple more changes to allow tests to pass:
> 
> 1. Placeholders for Italian versions of all the pages (About, FAQ, etc.) and posts.
> 2. A placeholder (the English version) for the Italian "goal 18" icon, which is mainly for symmetry in the homepage grid.

Thanks, but something is still broken because I can't see it icons 😢

**Comment by brockfanning** [comment]
@mauromussin Maybe it is caching? They seem to be working for me:

Screenshot from 2020-03-01 13-11-17

**Comment by mauromussin** [comment]
@brockfanning 
You're right, it works!
I've added high-contrast icons and a new release of translation.
I will finish it tomorrow.
Thank you so much 👍

**Comment by mauromussin** [comment]
@brockfanning 
But...why can't I see the italian translation on the "Italiano" version for SDG#1? 
I've put the _global_targets.yml_ in the it subdir, the same file is in my repo translation-un-sdg as in _config_data.yml_
```
# Links to Git repositories with translation data.
translations:
  - https://github.com/mauromussin/translations-open-sdg.git@1.0.0-rc8
  - https://github.com/mauromussin/translations-un-sdg.git@1.0.0-rc3
```
I can't understand why the local subdir is not working...

**Comment by brockfanning** [comment]
@mauromussin To see the indicators translated you'll need to complete the global_indicators.yml file (a lot of work, I know).

It does look like something weird is going on with targets, though. I will investigate.

**Pull request merged**
